TISSUE_HIGH_THRESH = 80
TISSUE_LOW_THRESH = 10

SCALE_FACTOR = 32
TILE_TEXT_COLOR = (0, 0, 0)
TILE_TEXT_SIZE = 36
TILE_TEXT_BACKGROUND_COLOR = (255, 255, 255)
TILE_TEXT_W_BORDER = 5
TILE_TEXT_H_BORDER = 4

FONT_PATH = None
